name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "First output"
          echo "Second output"
      - name: Print goodbye
        run: echo "Done - bye!"
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking python version
        run: python --version
